#version 450
#extension GL_EXT_samplerless_texture_functions : require
layout(local_size_x = 64) in;
layout(binding = 0, std430) buffer Data { uint words[]; } data;
layout(push_constant) uniform Args { uint samples, offset, count, bytes; } args;
#ifdef COLOR
layout(binding = 1) uniform utexture2DMS src;
#elif defined(MS)
layout(binding = 1) uniform texture2DMS src;
#else
layout(binding = 1) uniform texture2D src;
#endif
void main()
{
    uint i = gl_GlobalInvocationID.x;
    if (i >= args.count) return;
    ivec2 p = ivec2(i / args.samples, 0);
#ifdef COLOR
    uvec2 value = texelFetch(src, p, int(i % args.samples)).xy;
    data.words[args.offset + 2 * i] = value.x;
    data.words[args.offset + 2 * i + 1] = value.y;
#else
#ifdef MS
    float value = texelFetch(src, p, int(i % args.samples)).x;
#else
    float value = texelFetch(src, p, 0).x;
#endif
    data.words[args.offset + i] = floatBitsToUint(value);
#endif
}
