#ifndef HELIOS_RESOURCE_ASSOCIATION_H
#define HELIOS_RESOURCE_ASSOCIATION_H

/* Generated by cbindgen from protocol/src/resource_association.rs. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "helios_wddm.h"

#define HELIOS_RESOURCE_ASSOCIATION_STRUCTURE_TYPE 1213350193

#define HELIOS_RESOURCE_ASSOCIATION_ABI_VERSION 1

#define HELIOS_RESOURCE_ASSOCIATION_BYTES 72

#define HELIOS_RESOURCE_ASSOCIATION_FLAG_CPU_MAPPING (1U << 0)

#define HELIOS_RESOURCE_ASSOCIATION_FLAG_GUEST_PAGE_BACKED (1U << 1)
/* Opened, not created: already holds the creator's pixels. DXVK binds it as an
 * import (no initializer clear, no UNDEFINED transition) and strips the bit. */
#define HELIOS_RESOURCE_ASSOCIATION_FLAG_OPENED (1U << 2)
#define HELIOS_RESOURCE_ASSOCIATION_FLAG_MASK \
    (HELIOS_RESOURCE_ASSOCIATION_FLAG_CPU_MAPPING | \
     HELIOS_RESOURCE_ASSOCIATION_FLAG_GUEST_PAGE_BACKED | \
     HELIOS_RESOURCE_ASSOCIATION_FLAG_OPENED)

typedef struct HeliosResourceAssociationV1 {
  uint32_t s_type;
  uint32_t struct_bytes;
  const void *p_next;
  uint32_t abi_version;
  uint32_t reserved;
  uint64_t package_generation;
  uint64_t device_generation;
  uint64_t outer_allocation_token;
  uint64_t outer_allocation_bytes;
  void *cpu_mapping;
  uint32_t association_flags;
  uint32_t reserved1;
} HeliosResourceAssociationV1;

#if defined(__cplusplus)
#define HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(cond, msg) static_assert(cond, msg)
#define HELIOS_RESOURCE_ASSOCIATION_ALIGNOF(type) alignof(type)
#else
#define HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)
#define HELIOS_RESOURCE_ASSOCIATION_ALIGNOF(type) _Alignof(type)
#endif

HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(sizeof(HeliosResourceAssociationV1) == 72, "");
HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(HELIOS_RESOURCE_ASSOCIATION_ALIGNOF(HeliosResourceAssociationV1) == 8, "");
HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(offsetof(HeliosResourceAssociationV1, s_type) == 0, "");
HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(offsetof(HeliosResourceAssociationV1, struct_bytes) == 4, "");
HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(offsetof(HeliosResourceAssociationV1, p_next) == 8, "");
HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(offsetof(HeliosResourceAssociationV1, abi_version) == 16, "");
HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(offsetof(HeliosResourceAssociationV1, reserved) == 20, "");
HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(offsetof(HeliosResourceAssociationV1, package_generation) == 24, "");
HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(offsetof(HeliosResourceAssociationV1, device_generation) == 32, "");
HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(offsetof(HeliosResourceAssociationV1, outer_allocation_token) == 40, "");
HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(offsetof(HeliosResourceAssociationV1, outer_allocation_bytes) == 48, "");
HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(offsetof(HeliosResourceAssociationV1, cpu_mapping) == 56, "");
HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(offsetof(HeliosResourceAssociationV1, association_flags) == 64, "");
HELIOS_RESOURCE_ASSOCIATION_STATIC_ASSERT(offsetof(HeliosResourceAssociationV1, reserved1) == 68, "");

#endif  /* HELIOS_RESOURCE_ASSOCIATION_H */
