<#
.SYNOPSIS
  Stage and (optionally) register VK_LAYER_HELIOS_present, the Helios native
  Vulkan WSI layer.

.DESCRIPTION
  `-Dvulkan-layers=helios-present` produces VkLayer_HELIOS_present.dll and its
  loader manifest in the Mesa build tree. Nothing loads them from there. This
  script is the other half: it stages both into an install directory with an
  absolute `library_path`, proves the DLL's loader entry point actually runs,
  and then either prints the per-process recipe (default) or writes the
  machine-wide implicit-layer registry value.

  ⛔ WHY MACHINE-WIDE IMPLICIT REGISTRATION IS NOT THE DEFAULT.

  An implicit layer is loaded into EVERY Vulkan instance on the machine. On
  this box that includes dxvk-helios, which is how dwm composites the desktop —
  and docs/HELIOS_PRESENT_SYNC_RETIREMENT.md §2 item 8 makes "translators never
  enter this layer" an acyclicity rule, not a preference. The manifest's
  `disable_environment` (DISABLE_LAYER_HELIOS_PRESENT=1) cannot be used to
  carve dwm back out, for the reason measured in the header of
  run-helios-layer-app.ps1: the Vulkan loader ignores its environment variables
  entirely in an elevated process. So -Register Implicit hands an unfinished
  layer the desktop's compositor with no way to opt it back out short of
  deleting the registry value.

  Per-process staging (the default) is scoped, needs no registry write, and is
  what a native-Vulkan probe wants anyway.

.PARAMETER Register
  None      stage only, print the per-process recipe (default).
  Implicit  additionally write the Khronos ImplicitLayers registry value.
            Read the warning above first.
#>
param(
  [string]$DllPath = "C:\Users\Rupansh\helios-mesa-build\src\vulkan\helios-present-layer\VkLayer_HELIOS_present.dll",
  [string]$ManifestTemplate = "",
  [string]$InstallDir = "C:\ProgramData\HeliosVulkanLayer",
  [ValidateSet("None", "Implicit")]
  [string]$Register = "None",
  [ValidateSet("Machine", "User")]
  [string]$Scope = "Machine",
  [switch]$PruneOld,
  [switch]$NoVerify,
  [switch]$PlanOnly
)

$ErrorActionPreference = "Stop"
. "$PSScriptRoot\helios-deploy-common.ps1"

function Test-IsAdmin {
  $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
  $principal = [Security.Principal.WindowsPrincipal]::new($identity)
  return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

if (-not (Test-Path -LiteralPath $DllPath -PathType Leaf)) {
  throw "Layer DLL not found: $DllPath  (build it with: ninja -C <mesa build> src/vulkan/helios-present-layer/VkLayer_HELIOS_present.dll)"
}
$sourceDll = (Resolve-Path -LiteralPath $DllPath).Path

# The manifest is generated by meson next to the DLL. Taking it from there
# rather than re-emitting it here keeps ONE source of truth for the layer's
# advertised extensions and entry points: the .json.in in the Mesa tree.
if (-not $ManifestTemplate) {
  $ManifestTemplate = Join-Path (Split-Path -Parent $sourceDll) "VkLayer_HELIOS_present.json"
}
if (-not (Test-Path -LiteralPath $ManifestTemplate -PathType Leaf)) {
  throw "Layer manifest not found: $ManifestTemplate"
}

$installDirFull = [IO.Path]::GetFullPath($InstallDir)
$sourceHash = Get-HeliosFileHash $sourceDll
$hashPrefix = $sourceHash.Substring(0, 12).ToLowerInvariant()
# Hash-suffixed, for the same reason the ICD is: a loaded DLL cannot be
# overwritten, and a layer stays loaded for the lifetime of every process that
# created an instance with it.
$destDll = Join-Path $installDirFull "VkLayer_HELIOS_present-$hashPrefix.dll"
$manifest = Join-Path $installDirFull "VkLayer_HELIOS_present.json"

$registryPath = if ($Scope -eq "Machine") {
  "HKLM:\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
} else {
  "HKCU:\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
}

Write-HeliosPlan "Helios Vulkan present-layer install" @{
  Source = $sourceDll
  SourceHash = $sourceHash
  Destination = $destDll
  Manifest = $manifest
  ManifestTemplate = $ManifestTemplate
  Register = $Register
  RegistryPath = if ($Register -eq "None") { "(not written)" } else { $registryPath }
}
if ($PlanOnly) { return }

if ($Register -eq "Implicit" -and $Scope -eq "Machine" -and -not (Test-IsAdmin)) {
  throw "Machine-scope implicit registration writes HKLM and requires elevated PowerShell. Re-run as Administrator, or pass -Scope User."
}

New-Item -ItemType Directory -Force -Path $installDirFull | Out-Null
Grant-HeliosReadExecute $installDirFull
$copy = Copy-HeliosFileVerified $sourceDll $destDll 3 500
Grant-HeliosReadExecute $installDirFull

# Rewrite only `library_path`, to the absolute staged DLL. Everything else in
# the manifest — the layer name, api_version, the advertised instance/device
# extensions and their entry point lists — comes from the build and is not
# this script's to invent. A manifest that disagrees with the DLL it names is
# the silent failure mode this whole file exists to avoid.
$manifestObj = Get-Content -LiteralPath $ManifestTemplate -Raw | ConvertFrom-Json
if ([string]$manifestObj.layer.name -ne "VK_LAYER_HELIOS_present") {
  throw "Manifest template names layer '$($manifestObj.layer.name)', expected VK_LAYER_HELIOS_present: $ManifestTemplate"
}
$expectedLibraryPath = $destDll -replace "\\", "/"
$manifestObj.layer.library_path = $expectedLibraryPath
$manifestText = ($manifestObj | ConvertTo-Json -Depth 8) + [Environment]::NewLine

# Same durable-publish discipline as install-helios-icd.ps1: write-through to a
# temp, validate the readback, then replace atomically on the same volume. A
# deploy is commonly followed by a reboot, and a cached-but-unflushed manifest
# has been observed to survive as a NUL-filled file of the right length.
$manifestTmp = "$manifest.tmp.$PID.$([guid]::NewGuid().ToString('N'))"
$manifestBytes = [Text.UTF8Encoding]::new($false).GetBytes($manifestText)
$manifestStream = $null
$manifestBackup = $null
$manifestValidated = $false
$manifestPublished = $false
try {
  try {
    $manifestStream = [IO.FileStream]::new(
      $manifestTmp,
      [IO.FileMode]::CreateNew,
      [IO.FileAccess]::Write,
      [IO.FileShare]::None,
      4096,
      [IO.FileOptions]::WriteThrough)
    $manifestStream.Write($manifestBytes, 0, $manifestBytes.Length)
    $manifestStream.Flush($true)
  } finally {
    if ($manifestStream) { $manifestStream.Dispose() }
  }

  $tmpText = Get-Content -LiteralPath $manifestTmp -Raw
  if ($tmpText.IndexOf([char]0) -ge 0) { throw "Generated layer manifest contains NUL bytes: $manifestTmp" }
  $tmpParsed = $tmpText | ConvertFrom-Json
  if ([string]$tmpParsed.layer.library_path -ne $expectedLibraryPath) {
    throw "Generated layer manifest failed readback validation: $manifestTmp"
  }
  if (Test-Path -LiteralPath $manifest -PathType Leaf) {
    $manifestBackup = "$manifest.bak.$PID.$([guid]::NewGuid().ToString('N'))"
    [IO.File]::Replace($manifestTmp, $manifest, $manifestBackup, $true)
  } else {
    [IO.File]::Move($manifestTmp, $manifest)
  }
  $manifestPublished = $true

  $installedParsed = Get-Content -LiteralPath $manifest -Raw | ConvertFrom-Json
  if ([string]$installedParsed.layer.library_path -ne $expectedLibraryPath) {
    throw "Installed layer manifest failed final validation: $manifest"
  }
  Grant-HeliosReadExecute $installDirFull
  $manifestValidated = $true
} catch {
  $publishError = $_
  if ($manifestPublished -and $manifestBackup -and (Test-Path -LiteralPath $manifestBackup -PathType Leaf)) {
    $failedManifest = "$manifest.failed.$PID.$([guid]::NewGuid().ToString('N'))"
    try {
      [IO.File]::Replace($manifestBackup, $manifest, $failedManifest, $true)
      Remove-Item -LiteralPath $failedManifest -Force -ErrorAction SilentlyContinue
      $manifestBackup = $null
      Write-Warning "Layer manifest publish failed; restored the previous manifest"
    } catch {
      Write-Warning "Layer manifest rollback also failed; previous manifest retained at $manifestBackup"
    }
  } elseif ($manifestPublished -and -not $manifestBackup) {
    Remove-Item -LiteralPath $manifest -Force -ErrorAction SilentlyContinue
    Write-Warning "Initial layer manifest publish failed; removed the unvalidated manifest"
  }
  throw $publishError
} finally {
  Remove-Item -LiteralPath $manifestTmp -Force -ErrorAction SilentlyContinue
  if ($manifestValidated -and $manifestBackup) {
    Remove-Item -LiteralPath $manifestBackup -Force -ErrorAction SilentlyContinue
  }
}

if ($PruneOld) {
  foreach ($oldDll in Get-ChildItem -LiteralPath $installDirFull -Filter "VkLayer_HELIOS_present-*.dll" -ErrorAction SilentlyContinue) {
    if ($oldDll.FullName -ieq $destDll) { continue }
    $users = @(Get-HeliosFileUsers $oldDll.FullName)
    if ($users.Count -gt 0) {
      Write-Host "Keeping old layer DLL still loaded: $($oldDll.FullName)"
    } else {
      Remove-Item -LiteralPath $oldDll.FullName -Force
      Write-Host "Removed old layer DLL: $($oldDll.FullName)"
    }
  }
}

# ---------------------------------------------------------------------------
# Verification: negotiate the loader interface for real.
#
# This is the cheapest possible proof that the staged DLL is loadable and that
# its loader entry point EXECUTES — no Vulkan instance, no session, no app. It
# catches a missing import (d3d12.dll/dxgi.dll), a wrong architecture, a
# stripped export, and a negotiate implementation that fills in nothing, all of
# which would otherwise present identically: "the loader just never finds it".
# ---------------------------------------------------------------------------
if (-not $NoVerify) {
  if (-not ("HeliosLayerNegotiate" -as [type])) {
    Add-Type -TypeDefinition @"
using System;
using System.Runtime.InteropServices;

public static class HeliosLayerNegotiate
{
    [DllImport("kernel32", SetLastError = true, CharSet = CharSet.Unicode)]
    public static extern IntPtr LoadLibraryW(string path);
    [DllImport("kernel32", SetLastError = true)]
    public static extern bool FreeLibrary(IntPtr module);
    [DllImport("kernel32", SetLastError = true, CharSet = CharSet.Ansi)]
    public static extern IntPtr GetProcAddress(IntPtr module, string name);

    // VkNegotiateLayerInterface (vk_layer.h). Sequential layout on x64:
    //   sType 4 + pad 4, pNext 8, loaderLayerInterfaceVersion 4 + pad 4,
    //   then the three function pointers = 48 bytes.
    [StructLayout(LayoutKind.Sequential)]
    public struct NegotiateInterface
    {
        public uint sType;                      // LAYER_NEGOTIATE_INTERFACE_STRUCT = 1
        public IntPtr pNext;
        public uint loaderLayerInterfaceVersion;
        public IntPtr pfnGetInstanceProcAddr;
        public IntPtr pfnGetDeviceProcAddr;
        public IntPtr pfnGetPhysicalDeviceProcAddr;
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    public delegate int PfnNegotiate(ref NegotiateInterface iface);

    public static string Run(string dllPath, uint requestVersion)
    {
        IntPtr mod = LoadLibraryW(dllPath);
        if (mod == IntPtr.Zero)
            return "LOAD_FAILED win32=" + Marshal.GetLastWin32Error();
        try
        {
            IntPtr fn = GetProcAddress(mod, "vkNegotiateLoaderLayerInterfaceVersion");
            if (fn == IntPtr.Zero)
                return "NO_EXPORT vkNegotiateLoaderLayerInterfaceVersion";
            var negotiate = (PfnNegotiate)Marshal.GetDelegateForFunctionPointer(fn, typeof(PfnNegotiate));
            var iface = new NegotiateInterface();
            iface.sType = 1;
            iface.loaderLayerInterfaceVersion = requestVersion;
            int r = negotiate(ref iface);
            return string.Format(
                "VkResult={0} version={1} gipa={2} gdpa={3} gpdpa={4}",
                r,
                iface.loaderLayerInterfaceVersion,
                iface.pfnGetInstanceProcAddr == IntPtr.Zero ? "NULL" : "ok",
                iface.pfnGetDeviceProcAddr == IntPtr.Zero ? "NULL" : "ok",
                iface.pfnGetPhysicalDeviceProcAddr == IntPtr.Zero ? "NULL" : "ok");
        }
        finally { FreeLibrary(mod); }
    }
}
"@
  }

  # The loader asks for interface version 2 (the version that carries
  # pfnGetPhysicalDeviceProcAddr). A layer must clamp to what it supports and
  # report that back in the same field.
  $result = [HeliosLayerNegotiate]::Run($destDll, 2)
  Write-Host "Negotiate probe: $result"
  if ($result -notmatch '^VkResult=0 version=2 gipa=ok gdpa=ok gpdpa=ok$') {
    throw "Layer negotiate probe failed: $result"
  }
}

if ($Register -eq "Implicit") {
  Write-Warning "Registering an IMPLICIT layer machine-wide: every Vulkan process on this box, INCLUDING dxvk-helios under dwm, will load it. Remove the value under $registryPath to undo."
  New-Item -Path $registryPath -Force | Out-Null
  New-ItemProperty -LiteralPath $registryPath -Name $manifest -Value 0 -PropertyType DWord -Force | Out-Null
  Write-Host "Registered implicit layer manifest: $manifest"
} else {
  Write-Host ""
  Write-Host "Staged, NOT registered. To load it in one process only:"
  Write-Host "    VK_ADD_IMPLICIT_LAYER_PATH=$installDirFull"
  Write-Host "⚠ The Vulkan loader ignores that variable in an ELEVATED process (win_exec is elevated)."
  Write-Host "  Use tools/run-helios-layer-app.ps1, which runs the app unelevated in the interactive session."
}

Write-Host "Installed layer DLL: $($copy.Destination)"
Write-Host "SHA256: $sourceHash"
Get-Content -LiteralPath $manifest
