#!/usr/bin/env python3
"""Synchronize static INF/Cargo branding; --check rejects stale copies without writes."""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    values = {}
    for line in (ROOT / "metadata/helios.env").read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, value = line.split("=", 1)
        if key in values or not re.fullmatch(r"[A-Z0-9_]+", key) or not value or any(
            ord(c) < 32 or ord(c) > 126 or c in '\\"' for c in value
        ):
            raise ValueError(f"Invalid metadata assignment: {key}")
        values[key] = value
    product = values["HELIOS_PRODUCT"]
    if len(product) > 12:
        raise ValueError("Product name must fit EDID: at most 12 ASCII bytes")
    if len(values["HELIOS_PUBLISHER"]) > 12:
        raise ValueError("Publisher text must fit the EDID descriptor (12 bytes)")
    if not 1990 <= int(values["HELIOS_MONITOR_MODEL_YEAR"]) <= 2245:
        raise ValueError("EDID model year must be between 1990 and 2245")
    replacements = {
        "kmd_render/helios_kmd_render.inx": {
            r'^ProviderName = .*': f'ProviderName = "{values["HELIOS_PUBLISHER"]}"',
            r'^DeviceDesc   = .*': f'DeviceDesc   = "{product}"',
            r'^DiskName     = .*': f'DiskName     = "{product} Driver Package"',
            r'^HKR,, HardwareInformation.AdapterString, .*':
                'HKR,, HardwareInformation.AdapterString, %REG_SZ%, %DeviceDesc%',
        }
    }
    for crate, role in [("kmd_render", "KMD"), ("umd", "UMD"), ("umd12", "UMD12")]:
        replacements[f"{crate}/Cargo.toml"] = {
            r'^description = .*': f'description = "{product} {values[f"HELIOS_{role}_ROLE"]}"'
        }
    # Cargo author metadata belongs to the project, not to the upstream engines.
    for crate in ["kmd_render", "umd", "umd12", "umd_common", "protocol", "kmd_logic", "tools/win-mcp"]:
        fields = replacements.setdefault(f"{crate}/Cargo.toml", {})
        fields[r'^authors = .*'] = f'authors = ["{values["HELIOS_PUBLISHER"]}"]'
    stale = []
    for name, fields in replacements.items():
        path = ROOT / name
        original = path.read_text()
        updated = original
        if name.endswith("Cargo.toml") and not re.search(r'^authors = ', updated, re.MULTILINE):
            updated = updated.replace('[package]\n', '[package]\nauthors = []\n', 1)
        for pattern, replacement in fields.items():
            updated, count = re.subn(pattern, lambda _: replacement, updated, flags=re.MULTILINE)
            if count != 1:
                raise ValueError(f"{name}: expected exactly one field matching {pattern}")
        if updated != original:
            stale.append(name)
            if not args.check:
                path.write_text(updated)
    header = ROOT / "metadata/helios_branding.h"
    content = (
        "/* Generated by tools/sync-metadata.py from metadata/helios.env. */\n"
        "#pragma once\n"
        f'#define HELIOS_PRODUCT_NAME "{product}"\n'
        f'#define HELIOS_PUBLISHER_NAME "{values["HELIOS_PUBLISHER"]}"\n'
    )
    if not header.exists() or header.read_text() != content:
        stale.append("metadata/helios_branding.h")
        if not args.check:
            header.write_text(content)
    if stale:
        print(("Stale: " if args.check else "Updated: ") + ", ".join(stale))
    else:
        print("Metadata is synchronized.")
    return int(args.check and bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
