#!/usr/bin/env python3
"""Generated Venus A7 schema and KMD-private patching mutation gate."""

from __future__ import annotations

import os
import re
import sys
from dataclasses import dataclass


REPO_DEFAULT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
GENERATOR = "tools/generate-venus-a7-schema.py"
SCHEMA = "kmd_logic/src/venus_executor/a7_schema.rs"
EXECUTOR = "kmd_logic/src/venus_executor.rs"
KMD = "kmd_render/src/ddi/native_render.rs"
MESA_DEFINES = "icd/mesa/src/virtio/venus-protocol/vn_protocol_driver_defines.h"
MESA_DRIVER = "icd/mesa/src/virtio/venus-protocol/vn_protocol_driver.h"
MESA_COMMANDS = "icd/mesa/src/virtio/vulkan/vn_command_buffer.c"
RETIREMENT = "tools/retirement-gates.sh"
SOURCES = (
    GENERATOR,
    SCHEMA,
    EXECUTOR,
    KMD,
    MESA_DEFINES,
    MESA_DRIVER,
    MESA_COMMANDS,
    RETIREMENT,
)


def load_sources(repo: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for path in SOURCES:
        with open(os.path.join(repo, path), encoding="utf-8", errors="replace") as stream:
            out[path] = stream.read()
    return out


def compact(value: str) -> str:
    return re.sub(r"\s+", "", value)


def snake(name: str) -> str:
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    return re.sub(r"[^A-Za-z0-9_]", "_", name).lower()


def require(path: str, source: str, fragments: tuple[str, ...], errors: list[str]) -> None:
    value = compact(source)
    for fragment in fragments:
        if compact(fragment) not in value:
            errors.append(f"{path}: missing A7 schema invariant: {fragment}")


def require_order(path: str, source: str, fragments: tuple[str, ...], errors: list[str]) -> None:
    value = compact(source)
    cursor = 0
    for fragment in fragments:
        wanted = compact(fragment)
        at = value.find(wanted, cursor)
        if at < 0:
            errors.append(f"{path}: A7 schema order drifted at {fragment}")
            return
        cursor = at + len(wanted)


def function(source: str, name: str) -> str:
    match = re.search(rf"\bfn\s+{re.escape(name)}\s*\(", source)
    if not match:
        return ""
    start = source.find("{", match.end())
    if start < 0:
        return ""
    depth = 0
    state = "code"
    quote = ""
    i = start
    while i < len(source):
        ch = source[i]
        nxt = source[i + 1] if i + 1 < len(source) else ""
        if state == "line":
            if ch == "\n":
                state = "code"
        elif state == "block":
            if ch == "*" and nxt == "/":
                state = "code"
                i += 1
        elif state == "string":
            if ch == "\\":
                i += 1
            elif ch == quote:
                state = "code"
        elif ch == "/" and nxt == "/":
            state = "line"
            i += 1
        elif ch == "/" and nxt == "*":
            state = "block"
            i += 1
        elif ch in ('"', "'"):
            state = "string"
            quote = ch
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return source[match.start() : i + 1]
        i += 1
    return ""


def check_sources(s: dict[str, str]) -> list[str]:
    errors: list[str] = []

    generator_revision = re.search(r'EXPECTED_GENERATOR_REV\s*=\s*"([0-9a-f]{8})"', s[GENERATOR])
    schema_revision = re.search(r"venus-protocol revision:\s*([0-9a-f]{8})", s[SCHEMA])
    mesa_revision = re.search(r"generated by venus-protocol git-([0-9a-f]{8})", s[MESA_DRIVER])
    revisions = {
        match.group(1) if match else "missing"
        for match in (generator_revision, schema_revision, mesa_revision)
    }
    if revisions != {"70991d4c"}:
        errors.append(f"Venus generator/schema/Mesa revisions disagree: {sorted(revisions)!r}")

    require(
        GENERATOR,
        s[GENERATOR],
        (
            '"vkAllocateMemory": "Allocation"',
            '"vkFreeMemory": "Allocation"',
            '"vkBindBufferMemory2": "Allocation"',
            '"vkBindImageMemory2": "Allocation"',
            '"vkBeginCommandBuffer": "CommandRecord"',
            '"vkEndCommandBuffer": "CommandRecord"',
            '"vkQueueSubmit": "Queue"',
            '"vkQueueSubmit2": "Queue"',
            '"vkQueueBindSparse": "Queue"',
            '"vkCreateInstance"',
            '"vkCreateRingMESA"',
            '"vkNotifyRingMESA"',
            '"vkWaitRingSeqnoMESA"',
            '"vkWaitVirtqueueSeqnoMESA"',
            '"rustfmt", "--edition", "2021"',
        ),
        errors,
    )
    require(
        SCHEMA,
        s[SCHEMA],
        (
            "const MAX_A7_NESTING: u32 = 64",
            "if depth >= MAX_A7_NESTING",
            "pub enum A7CommandKind",
            "pub fn parse_a7_command(",
            "_ => Err(VenusReject::UnknownOpcode)",
        ),
        errors,
    )
    schema_code = re.sub(r"//.*?$|/\*.*?\*/", "", s[SCHEMA], flags=re.MULTILINE | re.DOTALL)
    for forbidden in (
        "extern \"C\"",
        "unsafe {",
        "std::process",
        "std::net",
        "virtio",
        "host_resid",
        "submit_command",
    ):
        if forbidden in schema_code:
            errors.append(f"{SCHEMA}: generated decoder gained execution/carrier token {forbidden}")
    if s[SCHEMA].count("if depth >= MAX_A7_NESTING") != 1754:
        errors.append(f"{SCHEMA}: generated nesting checks drifted")

    command_names = set(re.findall(r"VN_CMD_ENQUEUE\(\s*(vk\w+)", s[MESA_COMMANDS]))
    command_names.update(("vkBeginCommandBuffer", "vkEndCommandBuffer"))
    parsed_names = {
        match.group(1)
        for match in re.finditer(r"fn\s+parse_command_(vk_[a-z0-9_]+)\s*\(", s[SCHEMA])
    }
    missing = sorted(name for name in command_names if snake(name) not in parsed_names)
    if missing:
        errors.append(f"{SCHEMA}: generated command-buffer decoder misses {missing[:8]!r}")

    outer = function(s[EXECUTOR], "validate_venus_a7_outer_stream")
    require_order(
        EXECUTOR,
        outer,
        (
            "a7_schema::parse_a7_command",
            "A7CommandKind::Allocation",
            "A7CommandKind::CommandRecord",
            "A7CommandKind::Queue",
            "if c.offset != bytes.len()",
            "if recording || admission.queue_command_count != 1",
        ),
        errors,
    )
    require(
        EXECUTOR,
        outer,
        (
            "return Err(VenusReject::InvalidSequence)",
            "admission.operand_count",
        ),
        errors,
    )
    control = function(s[EXECUTOR], "validate_venus_control_stream")
    require(
        EXECUTOR,
        control,
        (
            "opcode != OP_SET_REPLY",
            "c.u32()? != 0",
            "flags != COMMAND_GENERATE_REPLY",
            "operands.count != 1",
            "c.offset != bytes.len()",
        ),
        errors,
    )

    require_order(
        KMD,
        s[KMD],
        (
            "validate_batch_record(record, &expectation)",
            "validate_venus_a7_outer_stream(",
            "admission.operand_count as usize != operands.len()",
            "operand.operand_kind != HELIOS_HOB1_OPERAND_KIND_GENERATED_RESOURCE",
            "operand.payload_offset != expected_absolute",
            "copy_within(payload_start..payload_end, 0)",
            "dst.copy_from_slice(&scratch.patch_order[index].to_le_bytes())",
        ),
        errors,
    )
    require(
        KMD,
        s[KMD],
        (
            "Preserve the complete zero-operand HOB1 in scheduler DMA",
            "separately owned host buffer below receives renderer-private ids",
            "HeliosOuterBatchExpectation",
            "UseStaleGeneration",
            "UseMissingOrForeign",
            "DuplicateUse",
            "OperandClosure",
            "OperandWidth",
            "PatchBounds",
        ),
        errors,
    )
    exact_counts = {
        "if admission.operand_count as usize != operands.len()": 2,
        "if operand.payload_offset != expected_absolute": 2,
        "copy_within(payload_start..payload_end, 0);": 2,
    }
    for fragment, expected in exact_counts.items():
        if s[KMD].count(fragment) != expected:
            errors.append(f"{KMD}: expected {expected} exact occurrences of {fragment}")

    gate_line = 'python3 "$REPO/tools/venus-executor-schema-gate.py" "$REPO" --mutations'
    if s[RETIREMENT].count(gate_line) != 1:
        errors.append(f"{RETIREMENT}: A7 KMD schema gate must be integrated exactly once")
    return errors


@dataclass(frozen=True)
class Mutation:
    name: str
    path: str
    old: str
    new: str


def mutation_cases() -> tuple[Mutation, ...]:
    return (
        Mutation("generator revision drift", GENERATOR, '"70991d4c"', '"00000000"'),
        Mutation("unknown opcode admitted", SCHEMA, "_ => Err(VenusReject::UnknownOpcode)", "_ => unreachable!()"),
        Mutation("nesting unbounded", SCHEMA, "if depth >= MAX_A7_NESTING", "if false"),
        Mutation("outer sequence incomplete", EXECUTOR, "if recording || admission.queue_command_count != 1", "if false"),
        Mutation("control placeholder admitted", EXECUTOR, "if opcode != OP_SET_REPLY || flags != 0 || !c.pointer()?", "if false"),
        Mutation("operand count ignored", KMD, "if admission.operand_count as usize != operands.len()", "if false"),
        Mutation("operand offset ignored", KMD, "if operand.payload_offset != expected_absolute", "if false"),
        Mutation("patch original HOB1", KMD, "record_buffer\n        .as_mut_slice()\n        .copy_within(payload_start..payload_end, 0);", "args.pDmaBuffer.cast::<u8>();"),
    )


def run_mutations(sources: dict[str, str]) -> None:
    for case in mutation_cases():
        source = sources[case.path]
        count = source.count(case.old)
        if count < 1:
            raise SystemExit(f"A7 schema mutation setup failed for {case.name}: anchor count {count}")
        mutated = dict(sources)
        mutated[case.path] = source.replace(case.old, case.new, 1)
        if not check_sources(mutated):
            raise SystemExit(f"A7 schema mutation was accepted: {case.name}")
    print(f"OK: {len(mutation_cases())} in-memory A7 KMD schema mutations rejected")


def main() -> None:
    repo = (
        os.path.abspath(sys.argv[1])
        if len(sys.argv) > 1 and not sys.argv[1].startswith("--")
        else REPO_DEFAULT
    )
    sources = load_sources(repo)
    errors = check_sources(sources)
    if errors:
        raise SystemExit("A7 KMD schema gate violated:\n" + "\n".join(errors))
    if "--mutations" in sys.argv[1:]:
        run_mutations(sources)
    print("OK: generated A7 schema is pinned, parse-only, and privately patched")


if __name__ == "__main__":
    main()
